# Generated by Django 5.1.3 on 2025-02-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_alter_calendarcontents_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarcontents',
            name='distance',
            field=models.FloatField(blank=True, verbose_name='등산한 거리'),
        ),
    ]
