# Generated by Django 5.1.3 on 2025-02-26 07:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_alter_calendarcontents_distance'),
        ('mountains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalendarContents',
            new_name='Event',
        ),
    ]
