# Generated by Django 5.1.6 on 2025-02-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_postimage_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="photo",
            field=models.ImageField(
                upload_to="community/photo/%Y/%m/%d/", verbose_name="사진"
            ),
        ),
    ]
