# Generated by Django 5.1.6 on 2025-02-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0005_post_report_count"),
        ("users", "0002_user_block_flag_user_comment_posts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="report_posts",
            field=models.ManyToManyField(
                blank=True,
                related_name="report_users",
                to="community.post",
                verbose_name="신고한 Post 목록",
            ),
        ),
    ]
