# Generated by Django 5.1.6 on 2025-02-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postimage",
            name="created",
            field=models.DateTimeField(auto_now=True, verbose_name="업로드일시"),
        ),
    ]
