# Generated by Django 5.1.3 on 2025-02-23 15:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mountains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hikedate', models.DateField(default=datetime.date.today)),
                ('distance', models.PositiveIntegerField()),
                ('duration', models.DurationField()),
                ('memo', models.TextField()),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountains.mountain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
