# Generated by Django 5.1.3 on 2025-02-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarcontents',
            name='distance',
            field=models.PositiveIntegerField(blank=True, verbose_name='등산한 거리'),
        ),
        migrations.AlterField(
            model_name='calendarcontents',
            name='duration',
            field=models.DurationField(blank=True, verbose_name='등산한 시간'),
        ),
        migrations.AlterField(
            model_name='calendarcontents',
            name='memo',
            field=models.TextField(blank=True, verbose_name='기타'),
        ),
    ]
