# Generated by Django 5.1.3 on 2025-02-24 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarcontents',
            name='experienced',
            field=models.BooleanField(default=False, verbose_name='가본 산'),
        ),
        migrations.AddField(
            model_name='calendarcontents',
            name='wish',
            field=models.BooleanField(default=False, verbose_name='가보고 싶은 산'),
        ),
        migrations.AlterField(
            model_name='calendarcontents',
            name='distance',
            field=models.PositiveIntegerField(verbose_name='등산한 거리'),
        ),
        migrations.AlterField(
            model_name='calendarcontents',
            name='duration',
            field=models.DurationField(verbose_name='등산한 시간'),
        ),
        migrations.AlterField(
            model_name='calendarcontents',
            name='hikedate',
            field=models.DateField(default=datetime.date.today, verbose_name='등산 날짜'),
        ),
    ]
