# Generated by Django 5.1.3 on 2025-02-24 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_calendarcontents_experienced_calendarcontents_wish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarcontents',
            name='experienced',
        ),
        migrations.RemoveField(
            model_name='calendarcontents',
            name='wish',
        ),
    ]
