# Generated by Django 5.1.6 on 2025-02-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mountains", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mountain",
            name="leadtime",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mountain",
            name="mtn_difficulty",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="mountain",
            name="height",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="mountain",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
