# Generated by Django 5.1.3 on 2025-02-24 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mountain',
            old_name='name',
            new_name='mountain',
        ),
    ]
