# Generated by Django 5.1.3 on 2025-02-26 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountain',
            name='detail_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mountain',
            name='leadtime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='mountain',
            name='mtn_image',
            field=models.ImageField(blank=True, upload_to='mountains/image/'),
        ),
    ]
