# Generated by Django 5.1.6 on 2025-02-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mountains", "0002_mountain_leadtime_mountain_mtn_difficulty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mountain",
            name="mtn_image",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
