# Generated by Django 5.1.6 on 2025-02-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mountains", "0003_mountain_mtn_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="mountain",
            name="detail_info",
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="mountain",
            name="height",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
