# Generated by Django 5.1.3 on 2025-02-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_hashtag_post_tags'),
        ('users', '0004_relationship_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_flag',
            field=models.BooleanField(default=False, verbose_name='정지된 사용자'),
        ),
        migrations.AddField(
            model_name='user',
            name='bookmark_posts',
            field=models.ManyToManyField(blank=True, related_name='bookmark_users', to='posts.post', verbose_name='저장한 Post 목록'),
        ),
        migrations.AddField(
            model_name='user',
            name='comment_posts',
            field=models.ManyToManyField(blank=True, related_name='comment_users', to='posts.post', verbose_name='댓글 단 Post 목록'),
        ),
        migrations.AddField(
            model_name='user',
            name='report_count',
            field=models.PositiveIntegerField(default=0, verbose_name='신고 횟수'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='posts.post', verbose_name='좋아요 누른 Post 목록'),
        ),
    ]
