# Generated by Django 5.1.3 on 2025-02-23 15:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0001_initial'),
        ('users', '0005_user_block_flag_user_bookmark_posts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('distance', models.PositiveIntegerField()),
                ('duration', models.DurationField()),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountains.mountain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
