# Generated by Django 5.1.3 on 2025-02-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_mymountain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyMountain',
        ),
    ]
