# Generated by Django 5.1.3 on 2025-02-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0001_initial'),
        ('users', '0008_remove_user_bookmark_posts_user_save_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experienced_mountains',
            field=models.ManyToManyField(blank=True, related_name='experienced_users', to='mountains.mountain', verbose_name='등산해 본 Mountain 목록'),
        ),
        migrations.AddField(
            model_name='user',
            name='wish_mountains',
            field=models.ManyToManyField(blank=True, related_name='wish_users', to='mountains.mountain', verbose_name='등산해 보고 싶은 Mountain 목록'),
        ),
    ]
