# Generated by Django 5.1.6 on 2025-02-22 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_alter_postimage_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="created",
        ),
        migrations.RemoveField(
            model_name="post",
            name="created",
        ),
        migrations.RemoveField(
            model_name="postimage",
            name="created",
        ),
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="작성일시",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일시"),
        ),
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="작성일시",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일시"),
        ),
        migrations.AddField(
            model_name="postimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="업로드일시",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일시"),
        ),
    ]
