# Generated by Django 5.1.6 on 2025-02-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_remove_comment_created_remove_post_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="report_count",
            field=models.PositiveIntegerField(default=0, verbose_name="신고 횟수"),
        ),
    ]
